### ISSUE TITLE
Tops section to extract

### ISSUE THREAD

**Issue by martik617** [donald-keighley/lasr#3]
Thank you for such a handy tool to read las files in R. 
I have formation tops in my las files and wondered if it's possible to extract this section. 

~Tops
#TOPS NAME                                          DEPTH:
 CARDIUM FM                                        1696.0:
 CARDIUM SD                                        1712.7:
 KASKAPAU FM                                       1737.4:
 DUNVEGAN FM                                       2019.2:
 SHAFTESBURY FM                                    2047.4:
 BASE FISH SCALES MARKER                           2135.1:
 PEACE RIVER FM                                    2177.0:
 CADOTTE MBR                                       2213.8:
 HARMON MBR                                        2248.7:
 SPIRIT RIVER FM                                   2286.3:
 BLUESKY FM                                        2531.3:
 GETHING FM                                        2549.9:
 CADOMIN FM                                        2650.6:
 FERNIE GRP                                        2657.6:
 NORDEGG MBR                                       2699.1:
 MONTNEY FM                                        2724.0:
 BELLOY FM                                         2856.9:
 DEBOLT FM                                         2878.6:
 SHUNDA FM                                         2978.6:
 PEKISKO FM                                        3065.9:
 BANFF FM                                          3115.9:
 WABAMUN GRP                                       3328.0:
 WINTERBURN GRP                                    3562.2:
 DUVERNAY FM                                       4085.5:
~Curve Information Block

**Comment by donald-keighley** [comment]
Unfortunately you have a non standard LAS file.  Tops can be stored in a LAS 3.0 file but they  are supposed to look like the other data sections.  Its described on pages 21 and 22 here:

https://cwls.org/wp-content/uploads/2014/09/LAS_3_File_Structure.pdf

So, you'd have to write something special for your case.
